title = "Notre-Dame de Paris"
baseURL = "https://gohugo-theme-ananke.pages.dev"
languageCode = "da-DK"
theme = ["ananke"]
resourceDir = "../resources"

DefaultContentLanguage = "da"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.da]
    title = "Ananke"
    weight = 1
    contentDir = "content/da"
    # languageDirection = 'rtl' for Right-To-Left languages
  [languages.en]
    title = "Ananke Fr"
    weight = 2
    contentDir = "content/en"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "IT Advice"
  favicon = ""
  site_logo = ""
  description = "Welcome to The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/GoHugoIO"
