baseURL = 'https://herningfk.dk/'
languageCode = 'da-DK'
title = 'Herning Faldskærmsklub'

theme = ["github.com/theNewDynamic/gohugo-theme-ananke/v2"]

DefaultContentLanguage = "da"
SectionPagesMenu = "main"
googleAnalytics = ""
enableRobotsTXT = true

publishDir = "./docs"

[languages]
  [languages.da]
    title = "HFK"
    weight = 1
    contentDir = "content/da"
    # languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  date_format = "2. January 2006"
  author = "Thomas Gilbert"
  # site_logo = "/images/logo.png"
  description = "Hjemmesiden for Herning Faldskærmsklub"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-green"
  recent_posts_number = 10
